web/router.ex
defmodule Musiclog.Router do
  use Musiclog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do  
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Musiclog do
    pipe_through [:browser, :browser_auth]

    get "/", PlayController, :index
    resources "/users", UserController, only: [:index, :show, :edit, :update]
    resources "/artists", ArtistController, only: [:index, :show]
    resources "/songs", SongController, only: [:index, :show]
    resources "/plays", PlayController, only: [:index, :show, :delete]

    get "/api-key", UserController, :api_key
    post "/api-key/update", UserController, :update_api_key

    get "/login", AuthController, :login_page
    post "/auth/login", AuthController, :login
    get "/logout", AuthController, :delete

    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback
    post "/auth/create", AuthController, :create
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/api", Musiclog do
    pipe_through [:api, :api_auth]
    put "/users/:user", APIController, :login
    post "/users/:user/play", APIController, :play
    delete "/users/:user", APIController, :logout
  end
end

web/views/layout_view.ex
defmodule Musiclog.LayoutView do
  use Musiclog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Listen History</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">Listen History</a>
          </div>
          <ul class="nav navbar-nav navbar-left">
            <li><a href="<%= play_path(@conn, :index) %>">Plays</a></li>
            <li><a href="<%= song_path(@conn, :index) %>">Songs</a></li>
            <li><a href="<%= artist_path(@conn, :index) %>">Artists</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= if logged_in?(@conn) do %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user(@conn).name %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="<%= user_path(@conn, :show, current_user(@conn).name) %>">Your profile</a></li>
                  <li><a href="<%= user_path(@conn, :api_key) %>">Sync your playing</a></li>
                  <hr>
                  <li><a href="<%= auth_path(@conn, :delete) %>">Logout</a></li>
                </ul>
              </li>
            <% else %>
              <li><a href="<%= auth_path(@conn, :login_page) %>">Sign In</a></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>